##Spring Configuration
server:
  port: 8082
spring:
  application:
    name: "ms_reportes"
  h2:
    console:
      enabled: true
      path: "/h2"
  profiles:
    include: null
entrypoint:
  sqs:
    region: "us-east-1"
    queueUrl: "${SQS_APPROVED_QUEUE_URL:https://sqs.us-east-1.amazonaws.com/646523381259/approved}"
    waitTimeSeconds: 20
    maxNumberOfMessages: 10
    visibilityTimeoutSeconds: 10
    numberOfThreads: 2
