##Spring Configuration
server:
  port: 8081
spring:
  application:
    name: ms_solicitudes
  devtools:
    add-properties: false
  h2:
    console:
      enabled: true
      path: /h2
  profiles:
    include: null
  r2dbc:
    url: r2dbc:mysql://localhost:3307/crediya_solicitudes_db?&serverTimezone=UTC
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

# Configuración personalizada
security:
  user:
    protected-password: "[PROTECTED]"
adapter:
  restconsumer:
    url: "http://localhost:8080"
    timeout: 5000